name: Concurency One
run-name: Concurency One (${{ github.event.inputs.environment }})
on: 
   workflow_dispatch:
    inputs:
      environment:
         description: "Environment"
         type: environment
         required: true
concurrency: 
    group: ${{ github.event.inputs.environment }}
jobs:
   sleep:
      runs-on: ubuntu-latest
      steps:
         - run: sleep 30