name: Example Workflow
on: 
 workflow_dispatch:
    inputs:
      CHANNEL_ALLURE_ID:
        description: 'Channel Allure ID'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Call Composite Action
        uses: ./.github/workflows/actions/test/actions.yml
        with:
          channel_allure_id: "25486" 