name: Send PR
on:
  pull_request:
    types: [labeled]

jobs:
  send-mesage:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Object
        env:
          EVENT: ${{ toJson(github.event) }}
        run: echo "$EVENT"
