name: Send PR
on:
  pull_request:
    types: [labeled]

jobs:
  send-mesage:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        run: |
          echo '${{ toJson(runner) }}'
          echo '${{ toJson(github.event) }}'
          echo '${{ github.event.pull_request.title }}'
          echo '${{ github.event.pull_request.additions }}'
          echo '${{ github.event.pull_request.number }}'
