name: Send PR
on:
  pull_request:
    types: [labeled]

jobs:
  send-mesage:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        run: |
          echo "${{ toJson(github.event) }}"
