name: Varibles and secrets
on: [push]

jobs:
    logs-vars:
        runs-on: ubuntu-latest
        env:
            BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
            ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
        steps:
            - name: RUN
              if: env.BOOLEAN_SECRET == 'true'
              run: echo "I ran"
            - name: Log vars
              run: |
                  echo "BOOLEAN_SECRET: $BOOLEAN_SECRET"
                  echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
                  echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
